### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by ppeer** [Casinelli/Laravel-Wikipedia#2]
is there any language support eg. how to pull requests from nl.wikipedia.org?

regards
Peter

**Comment by Casinelli** [comment]
Not right now. Should be possible, will try adding language support this week.

**Comment by ppeer** [comment]
thanks, for now I've changed the $url in QueryBuilder.php from en.wikipedia.org to nl.wikipedia.org,
forked your project and changed the composer Git Source for the package.
